### ISSUE TITLE
Bug: Codec list gets duplicated when using SAIL_ONLY_CODECS

### ISSUE THREAD

**Issue by JoniSt** [HappySeaFox/sail#103]
Hi again,

I've found a minor bug in SAIL's cmake build scripts. Defining `SAIL_ONLY_CODECS` (or `SAIL_EXCEPT_CODECS`) causes the list of codecs to get duplicated like this:

```
~/sail/build$ cmake -DCMAKE_BUILD_TYPE=Debug -DSAIL_ONLY_CODECS="png;jpeg;bmp" ..
***************************************
*
* Configuration statistics:
(...snip...)
* Enabled codecs:              BMP,JPEG,PNG,BMP,JPEG,PNG
```
This in turn causes SAIL to load all codecs twice when using `SAIL_FLAG_PRELOAD_CODECS`.

I've managed to track the bug down: `cmake/sail_codec.cmake` gets called for every enabled codec and adds them to the `SAIL_ENABLED_CODECS` list; however, `src/sail-codecs/CMakeLists.txt` also adds every enabled codec to that list. The latter probably shouldn't populate the list.

Here's a [simple patch](https://gist.github.com/JoniSt/a6cf867f215e9360f69dbacc2d5244a9) that fixes the bug. I've just renamed the temporary variable that the ONLY_CODECS/EXCEPT_CODECS code uses so it doesn't collide with the list that `sail_codec.cmake` generates anymore.

Thank you for your great work on this awesome library!

**Comment by HappySeaFox** [comment]
@JoniSt Fix has been commited in `feature/fix-sail-only-codecs`. Please check it works as expected. On my side I checked it with different combinations of `SAIL_ONLY_CODECS` and `SAIL_EXCEPT_CODECS`, it looks good.

**Comment by JoniSt** [comment]
Works great in my project too, codecs are now loaded only once. Thank you for the super quick fix!
