### ISSUE TITLE
When the  1.0.0 version is expected?

### ISSUE THREAD

**Issue by rahmanih** [HappySeaFox/sail#112]
Hi,

First of all, congrats for this great library. it is simply amazing.

I just want to know when is the official release 1.0.0 is planned?

regards.

**Comment by HappySeaFox** [comment]
@rahmanih Hi! 😀 Thanks for the feedback! I plan to release 0.9.0 this year hopefully. The release will be stable and hopefully long-term with stable API and ABI.

I'll continue add new codecs preserving backwards compatibility after the release.

1.0.0 will be released after 0.9.0. But I have no ideas what to expect from it for now. 😀

**Comment by rahmanih** [comment]
👍 that's great as plan 😊
I'm keeping watching, and If I'll find some time I'll try to contribute if you permit of course.
