### ISSUE TITLE
make a release

### ISSUE THREAD

**Issue by plekakis** [HappySeaFox/sail#114]
Would be helpful to make a pre-built release if time permits.
Debug/release configurations and static/dynamic lib would be ideal.

**Comment by HappySeaFox** [comment]
Hi! I think it's totally possible. I'll to make it on the next pre-release (coming soon)

**Comment by HappySeaFox** [comment]
The next pre-release will offer debug and release dynamic versions available on the Releases page. Static version can be obtained in vcpkg only for now for technical reasons.
