### ISSUE TITLE
Copying of library contents with GCC's --whole-archive doesn't work, breaks non-shared build

### ISSUE THREAD

**Issue by JoniSt** [HappySeaFox/sail#148]
Hi again,

the static build woes on Linux aren't quite over yet, sadly... :cry: 

I just switched to using ```BUILD_SHARED_LIBS=OFF``` when I noticed that my build was still using the old (no longer functional) ```SAIL_STATIC=ON``` flag.  As soon as I did that, my project broke with the following linker errors:

```
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x8): undefined reference to `sail_codec_read_seek_next_frame_v6_bmp'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x10): undefined reference to `sail_codec_read_frame_v6_bmp'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x18): undefined reference to `sail_codec_read_finish_v6_bmp'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x20): undefined reference to `sail_codec_write_init_v6_bmp'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x28): undefined reference to `sail_codec_write_seek_next_frame_v6_bmp'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x30): undefined reference to `sail_codec_write_frame_v6_bmp'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x38): undefined reference to `sail_codec_write_finish_v6_bmp'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x40): undefined reference to `sail_codec_read_init_v6_jpeg'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x48): undefined reference to `sail_codec_read_seek_next_frame_v6_jpeg'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x50): undefined reference to `sail_codec_read_frame_v6_jpeg'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x58): undefined reference to `sail_codec_read_finish_v6_jpeg'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x60): undefined reference to `sail_codec_write_init_v6_jpeg'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x68): undefined reference to `sail_codec_write_seek_next_frame_v6_jpeg'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x70): undefined reference to `sail_codec_write_frame_v6_jpeg'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x78): undefined reference to `sail_codec_write_finish_v6_jpeg'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x80): undefined reference to `sail_codec_read_init_v6_png'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x88): undefined reference to `sail_codec_read_seek_next_frame_v6_png'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x90): undefined reference to `sail_codec_read_frame_v6_png'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0x98): undefined reference to `sail_codec_read_finish_v6_png'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0xa0): undefined reference to `sail_codec_write_init_v6_png'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0xa8): undefined reference to `sail_codec_write_seek_next_frame_v6_png'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0xb0): undefined reference to `sail_codec_write_frame_v6_png'
/usr/bin/ld: /home/jonathan/CLionProjects/vlktest/cmake-build-optimizeddebug/thirdparty/sail/install/lib/libsail-codecs.a(enabled_codecs.c.o):(.data.rel.ro+0xb8): undefined reference to `sail_codec_write_finish_v6_png'
```

I then tried to do another clean build of SAIL with the following CMake command-line:
```cmake -DBUILD_SHARED_LIBS=OFF -DSAIL_THIRD_PARTY_CODECS_PATH=OFF -DSAIL_ONLY_CODECS="png;jpeg;bmp" ..```

The build of SAIL itself worked; however, the ```libsail-codecs.a``` archive doesn't contain any of the codecs' symbols, it just references them:
```
jonathan@x399-designare-debian11:~/bigdisk/sail-repo/sail/build/src/sail-codecs-archive$ nm -g libsail-codecs.a 

enabled_codecs.c.o:
                 U sail_codec_read_finish_v6_bmp
                 U sail_codec_read_finish_v6_jpeg
                 U sail_codec_read_finish_v6_png
                 U sail_codec_read_frame_v6_bmp
                 U sail_codec_read_frame_v6_jpeg
                 U sail_codec_read_frame_v6_png
                 U sail_codec_read_init_v6_bmp
                 U sail_codec_read_init_v6_jpeg
                 U sail_codec_read_init_v6_png
                 U sail_codec_read_seek_next_frame_v6_bmp
                 U sail_codec_read_seek_next_frame_v6_jpeg
                 U sail_codec_read_seek_next_frame_v6_png
                 U sail_codec_write_finish_v6_bmp
                 U sail_codec_write_finish_v6_jpeg
                 U sail_codec_write_finish_v6_png
                 U sail_codec_write_frame_v6_bmp
                 U sail_codec_write_frame_v6_jpeg
                 U sail_codec_write_frame_v6_png
                 U sail_codec_write_init_v6_bmp
                 U sail_codec_write_init_v6_jpeg
                 U sail_codec_write_init_v6_png
                 U sail_codec_write_seek_next_frame_v6_bmp
                 U sail_codec_write_seek_next_frame_v6_jpeg
                 U sail_codec_write_seek_next_frame_v6_png
0000000000000000 D sail_enabled_codecs
0000000000000020 D sail_enabled_codecs_info
0000000000000000 D sail_enabled_codecs_layouts
```

On the other hand, ```libsail-codecs-objects.a``` does contain the codecs' symbols.

Apparently, the GNU linker's ```--whole-archive``` option only adds *dependencies* on all public symbols of the libraries that are being linked against, it does not copy them into the new archive. (It only does the copying when building an executable or shared object, not when building an archive.)

On the other hand, if I build with ```BUILD_SHARED_LIBS=ON```, the ```libsail-codecs.a``` that is produced does contain all the required symbols and works fine with static linking.

As far as I can tell, it should be possible to just remove the library copying step and always build the combined archive like in the shared library case (by compiling everything directly into sail-codecs). There should be no reason to build the static library in two different ways depending on whether the shared library is built as well or not.

I did this change on my fork of the repo and it works just fine on Linux (and fixes the problem): https://github.com/JoniSt/sail/tree/remove-library-copying

Do you think this would break anything? (Or is it intentional that ```sail-codecs``` doesn't contain the codecs themselves in a non-shared build? Should I instead link against ```sail-codecs-objects```?)

Jonathan

**Comment by HappySeaFox** [comment]
Hi! 😀

I removed SAIL_STATIC just to be consistent with CMake guidelines regarding BUILD_SHARED_LIBS. From now on, one should use BUILD_SHARED_LIBS to build a static version.

After the clean rebuild, does everything works fine? I mean, do client apps link and run successfully with a static build?

**Comment by JoniSt** [comment]
Thanks for your quick reply! :+1:

SAIL's example binaries build fine in either mode (I tested it with the "sail" binary); however, external applications don't link when SAIL was built with BUILD_SHARED_LIBS=OFF. They link fine when it was built with shared libs enabled, even when using the static libraries instead of the shared ones.

When building SAIL's examples with shared libs disabled, CMake knows that sail-codecs depends on sail-codecs-objects and both will be linked into the executable. However, external applications that only link against libsail-codecs.a (and not against libsail-codecs-objects.a) fail to link because the codecs are contained in sail-codecs-objects and not in sail-codecs. (And that's because "--whole-archive" doesn't copy archive contents in the GNU Linker.)

Or am I just building my own application wrong? Right now I'm under the impression that I should link against the sail-codecs library only, and not against sail-codecs-objects.

This is the CMakeFile that imports SAIL into my project:
```
find_package(PNG REQUIRED)
find_package(JPEG REQUIRED)

string(TOUPPER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE_UPPER)

ExternalProject_Add(sail-project
        GIT_REPOSITORY https://github.com/JoniSt/sail
        GIT_TAG f2f0eadfdf8d8eb0fd68082da8a3939a767ae8fa
        GIT_SUBMODULES_RECURSE ON
        GIT_REMOTE_UPDATE_STRATEGY CHECKOUT
        INSTALL_DIR "${CMAKE_CURRENT_BINARY_DIR}/install"
        LIST_SEPARATOR |
        CMAKE_CACHE_ARGS
                    "-DCMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
                    "-DCMAKE_C_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_C_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
                    "-DCMAKE_EXE_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_EXE_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
                    "-DCMAKE_SHARED_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}:STRING=${CMAKE_SHARED_LINKER_FLAGS_${CMAKE_BUILD_TYPE_UPPER}}"
                    "-DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}"
                    "-DSAIL_BUILD_EXAMPLES:BOOL=OFF"
                    "-DSAIL_BUILD_TESTS:BOOL=OFF"
                    "-DSAIL_COLORED_OUTPUT:BOOL=OFF"
                    "-DBUILD_SHARED_LIBS:BOOL=OFF"
                    "-DSAIL_ONLY_CODECS:STRING=png|jpeg|bmp"
                    "-DSAIL_THIRD_PARTY_CODECS_PATH:BOOL=OFF"
                    "-DCMAKE_INSTALL_PREFIX:STRING=<INSTALL_DIR>"
        )
add_library(ext-sail-c++ INTERFACE)
add_dependencies(ext-sail-c++ sail-project)
ExternalProject_Get_property(sail-project INSTALL_DIR)
ExternalProject_Get_property(sail-project SOURCE_DIR)
target_include_directories(ext-sail-c++ SYSTEM INTERFACE "${INSTALL_DIR}/include/sail")
target_link_directories(ext-sail-c++ INTERFACE "${INSTALL_DIR}/lib")
target_link_options(ext-sail-c++ INTERFACE -Wl,--whole-archive -lsail-codecs -Wl,--no-whole-archive)
target_link_libraries(ext-sail-c++ INTERFACE sail-c++ sail-manip sail sail-common jpeg png ${CMAKE_DL_LIBS})
set(OGLGAME_LICENSE_INPUT "${OGLGAME_LICENSE_INPUT};${SOURCE_DIR}/LICENSE.txt;${SOURCE_DIR}/LICENSE.INIH.txt" PARENT_SCOPE)
set(OGLGAME_LICENSE_DEPS "${OGLGAME_LICENSE_DEPS};sail-project" PARENT_SCOPE)
```

**Comment by HappySeaFox** [comment]
>However, external applications that only link against libsail-codecs.a

External apps are encouraged to use CMake configs and `find_package`. The idea is that a client always links to `sail-c++` (for C++ apps), or `sail` (for C apps) and all the required dependencies are pulled automatically for any type of build, shared or static.

I've just tried to compile an external example application under examples/ and succeeded. The example uses CMake configs and `find_package`. You can try too like that:

```
find_package(SailC++ REQUIRED)                                                                                                                       
target_link_libraries(YOUR-TARGET SAIL::sail-c++)                                                                                          ```
```

If you don't use CMake configs and `find_package`, try linking against the following:

```
-lsail-c++ -lsail -lsail-codecs -Wl,--whole-archive -lsail-codecs-objects -Wl,--no-whole-archive
```

This is what CMake configs actually do for you if you use them and `find_package`.

P.S. I've just realized that the changes I made in the last couple of months possibly eliminate the need of sail-codecs-objects. I'll investigate more on this.

**Comment by JoniSt** [comment]
Alright, so it was just me linking my application wrong after all! :smile: It's sadly impossible to use ```find_package``` together with ```ExternalProject_Add``` in CMake so I'm stuck specifying the libraries manually. Thanks! :+1:

And I agree, sail-codecs-objects is most likely not needed anymore. I've already removed it in my fork without encountering any problems, neither for static nor for shared builds. You could just pull the changes into your own repo and run CI on it, if you like, to see if anything breaks.

**Comment by HappySeaFox** [comment]
Thanks again for bringing this up! I think we can proceed with removing `sail-codecs-objects`. I think you can make a new PR as you're the original author of this idea. You can update to the latest master, make a new branch, and cherry-pick f1ea2f4. Additionally to your changes, I added a comment, and removed `codecs_objects_stub.c`. Thanks!

**Comment by JoniSt** [comment]
Hey! I'm sadly not too proficient with git - would it be okay if you made the pull request instead? It'd be far simpler, given that you already have the [remove-sail-codecs-objects](/HappySeaFox/sail/tree/feature/remove-sail-codecs-objects) branch that can be merged without conflicts.

Thanks a lot! :+1:

**Comment by HappySeaFox** [comment]
Sure!
