### ISSUE TITLE
png codec doesn't support non indexed grayscale

### ISSUE THREAD

**Issue by igor-elovikov** [HappySeaFox/sail#163]
basically if I just check formats with `sail::codec_info::from_extension("png").write_features().output_pixel_formats()` it just gives me this list: `13,14,15,16,31,32,33,34,47,48,49,50,55,56,57,58`

I've tried to write png image from grayscale buffer but didn't actually find an obvious way to do that (apart from converting it to rgb which I'd like to avoid)

is that intended? or it's something with my build (I just installed it from vcpkg)

**Comment by HappySeaFox** [comment]
Hi! SAIL always tries to write pixels as closer to the source pixels as possible. With png, it always writes source pixels. If you want to save a grayscale image as a 24bit rgb, the only way is to convert the image to 24bit beforehand. There are two conversion methods: 1. Modifying: Overwrite the original image 2. Const: Return a converted image

Hope this helps

**Comment by igor-elovikov** [comment]
Hi! thanks for your reply.

Not sure though if I've explained my issue clearly. I have a procedurally generated image in memory coming from external tool. It's a grayscale image and it can have a different precision. 

So I wanted to save it as a grayscale png.

This is what I did:
```c
auto image = sail::image(texture.buffer, SAIL_PIXEL_FORMAT_BPP8_GRAYSCALE, texture.level0Width, texture.level0Height);

image.save("myfile.png"); // this won't work (sail says it's not supported pixel format)
image.convert(SAIL_PIXEL_FORMAT_BPP8_INDEXED); // this one also not supported

// the only workaround I've found is this and it's not ideal:
image.convert(SAIL_PIXEL_FORMAT_BPP24_RGB);
image.save("myfile.png"); 
```

The same goes with 16 bit grayscale. Am I missing something here? 

Thanks!

**Comment by HappySeaFox** [comment]
Oh, I see. Let me check and get back to you.

**Comment by HappySeaFox** [comment]
It looks like an artifact of the old-era SAIL. Technically, now we have no reasons for not supporting grayscale image.

**Comment by HappySeaFox** [comment]
Please wait for the next available in `vcpkg`.

**Comment by HappySeaFox** [comment]
Great!😃

Yes, `sail_set_log_barrier` is the way to silence logs below the specified level.

**Comment by HappySeaFox** [comment]
https://github.com/microsoft/vcpkg/pull/24005
