### ISSUE TITLE
Conan package (Question)

### ISSUE THREAD

**Issue by FrideakisAB** [HappySeaFox/sail#167]
Are you planning to make a library package for Conan package manager?

**Comment by HappySeaFox** [comment]
Hi! Conan is not on the priority list for now. It would be great if a Conan person contributes.

**Comment by HappySeaFox** [comment]
Let's keep the issue open until Conan support is delivered 😃

**Comment by HappySeaFox** [comment]
https://github.com/HappySeaFox/conan-center-index/tree/master/recipes/sail

**Comment by HappySeaFox** [comment]
WIP https://github.com/conan-io/conan-center-index/pull/10364

**Comment by HappySeaFox** [comment]
Ready, waiting for approval: https://github.com/conan-io/conan-center-index/pull/10364

**Comment by HappySeaFox** [comment]
https://github.com/conan-io/conan-center-index/pull/10364 has been merged. Waiting for index update.

**Comment by HappySeaFox** [comment]
SAIL has been added to Conan! 3 tons of kudos go to @SpaceIM for his great help with the Conan integration.

See https://conan.io/center/sail
