### ISSUE TITLE
⭐ Your feedback is needed! ⭐

### ISSUE THREAD

**Issue by HappySeaFox** [HappySeaFox/sail#176]
SAIL is under development and your feedback is highly welcomed! Please discuss any feature requests, current difficulties etc. here 😃

**Comment by maisonbleudeluca** [comment]
Would it be possible to add .DDS file loading to this library?

**Comment by HappySeaFox** [comment]
@maisonbleudeluca Yeah, it would be great if anyone contributes dds support. I would probably not be able to do that myself.
