### ISSUE TITLE
Sail fails to decode some APNGs

### ISSUE THREAD

**Issue by qbnu** [HappySeaFox/sail#184]
Sail fails to decode Animated PNG files which use a [Color Type](https://pmt.sourceforge.io/specs/png-1.2-pdg.html#C.IHDR) other than 6 and [`APNG_BLEND_OP_OVER`](https://wiki.mozilla.org/APNG_Specification#.60fcTL.60:_The_Frame_Control_Chunk). This is because [`png_private_blend_over`](https://github.com/HappySeaFox/sail/blob/6e254a003b5e370e7acb667b8e9292287f6b2c6f/src/sail-codecs/png/helpers.c#L541) only supports RGBA, and doesn't check the [`tRNS` chunk](https://pmt.sourceforge.io/specs/png-1.2-pdg.html#C.Anc-trns). Even if the PNG doesn't have any transparency information, blend_source should be used instead (equivalent to blend_over assuming all pixels are opaque).

Examples from https://philip.html5.org/tests/apng/tests.html:
[8-bit greyscale and alpha, with blending](https://philip.html5.org/tests/apng/035.png)
[1-bit palette and alpha, with blending](https://philip.html5.org/tests/apng/038.png)
```c
const char* filename = "038.png";
sail_image* image = NULL;
const sail_codec_info* codec_info = NULL;
void* state = NULL;
sail_codec_info_from_extension("png", &codec_info); // SAIL_OK
sail_start_loading_from_file(filename, codec_info, &state); // SAIL_OK
sail_load_next_frame(state, &image); // SAIL_OK
sail_load_next_frame(state, &image); // SAIL_ERROR_UNSUPPORTED_BIT_DEPTH
```

And here's a 16-bit grayscale+alpha APNG that will incorrectly be blended as if it's 8-bit RGBA:
![grayanim16](https://user-images.githubusercontent.com/93988953/210078257-e5255832-7d07-478f-a07b-64cdedf51863.png)

**Comment by HappySeaFox** [comment]
I agree there are some blending issues. I've just fixed a memory corruption issue (at least on MSVC 2019) on `free()` and allowed blending for `BPP16-GRAYSCALE-ALPHA` and `BPP32-GRAYSCALE-ALPHA` pixel formats. I will probably continue looking into it (sorry cannot guarantee).

Regarding the [8-bit greyscale and alpha, with blending](https://philip.html5.org/tests/apng/035.png) image: it has three frames:
1. The first frame is hidden
2. The second frame is black (gray component: 0, alpha: 255)
3. The 3rd frame consists of semi-transparent white pixels which will look like gray after blending with black pixels (gray component: 255, alpha: 128).

https://philip.html5.org/tests/apng/tests.html specifies that the image should be rendered as `This should be solid grey. ` but I have a question why. The second frame is black. The third (blended) frame is gray. I would expect flashing black and gray frames and this is what I see currently in the local fixed SAIL version.

**Comment by qbnu** [comment]
If the image viewer respects `num_plays` in the acTL chunk then it should just play once and pause on the last frame.

**Comment by HappySeaFox** [comment]
Oh, I see. This explains a lot. The next rc will have blending of grayscale frames and I'll add num_plays as a [specific property](https://github.com/HappySeaFox/sail/blob/master/src/libsail-common/source_image.h#L107) for those who are interested.

**Comment by HappySeaFox** [comment]
Did you install sail through vcpkg?

**Comment by qbnu** [comment]
No, I built it from source.

**Comment by HappySeaFox** [comment]
You can try the latest master with blending of grayscale images.

**Comment by HappySeaFox** [comment]
Please reopen if needed
