### ISSUE TITLE
Codec validation error

### ISSUE THREAD

**Issue by jimli570** [HappySeaFox/sail#190]
Hi,

I am trying to use sail in linux, I get the following runtime error:

SAIL: [I] [context_private.c:711] Version: 0.9.0
SAIL: [I] [context_private.c:714] Build type: VCPKG
SAIL: [I] [context_private.c:720] Static build: yes
SAIL: [I] [context_private.c:726] Combine codecs: yes
SAIL: [I] [context_private.c:732] Thread-safe: yes
SAIL: [I] [context_private.c:738] SAIL_THIRD_PARTY_CODECS_PATH: enabled
SAIL: [E] [codec_info_private.c:292] Codec validation error: TIFF codec has empty compressions list
SAIL: [E] [codec_info_private.c:293] SAIL_ERROR_INCOMPLETE_CODEC_INFO

PS: Thanks for a good library!

**Comment by HappySeaFox** [comment]
Hi! What's your distro?

**Comment by HappySeaFox** [comment]
Fixed in the latest master. You can use it by updating your vcpkg copy like that (or wait for the fix to be merged into the official vcpkg repo):

```diff
diff --git a/ports/sail/portfile.cmake b/ports/sail/portfile.cmake
index 943d30dcd..0f33416a2 100644
--- a/ports/sail/portfile.cmake
+++ b/ports/sail/portfile.cmake
@@ -1,8 +1,8 @@
 vcpkg_from_github(
     OUT_SOURCE_PATH SOURCE_PATH
     REPO HappySeaFox/sail
-    REF v0.9.0-rc2
-    SHA512 9cbf48b716ff13ff5d494166b6777c70f225c67842c00004706e00a8b411e5c59315c524865694c4698d661f7b675961df14ef0405b4a90d627107499587b544
+    REF master
+    SHA512 0026d20bd8ca49e2c8da490aaf86e731c7db12c65539185548b724098ba72f4ce31424465873436a5256b8f3f90de4f1138c78c02a49489fadb8dcf6a4518867
     HEAD_REF master
 )
 
```
