### ISSUE TITLE
[Documentation] An error in the macOs->HomeBrew installation command

### ISSUE THREAD

**Issue by iwoplaza** [HappySeaFox/sail#191]
Currently, the following is listed on the website.
```sh
brew install HapySeaFox/sail/sail
```
There seems to be a typo which errors out with a "repository does not exist" error (the 'p' in "Hap'p'ySeaFox" is missing). Could confuse newcomers 😃

**Comment by HappySeaFox** [comment]
Fixed, thanks 👍
