### ISSUE TITLE
including sail.h when using vcpkg

### ISSUE THREAD

**Issue by Murk42** [HappySeaFox/sail#193]
When using vcpkg to manage the sail library, including sail looks like:
 `#include <sail/sail/sail.h` (notice the two "sail/" folders)
This leads to compiler errors in the sail.h file because it cannot open include file notifying us that it cant find them. I found a temporary fix by moving the "include/sail/sail" folder to "include/" and therefore I can simply do `#include <sail/sail.h>` and there aren't any errors anymore.

**Comment by HappySeaFox** [comment]
Please see https://github.com/HappySeaFox/sail/issues/75

TL;DR Use CMake integration or add `VcpkgInstalledDir/include/sail` to the project include path. CMake does that automatically.

**Comment by Murk42** [comment]
Thank you for the quick response!
