### ISSUE TITLE
Cannot open files with non-ASCII paths on Windows

### ISSUE THREAD

**Issue by Error-mdl** [HappySeaFox/sail#206]
It is impossible to use sail to directly open images with non ASCII characters windows. You're using the basic `fopen` function, which on windows interpets the char* path as ASCII characters remapped by the current locale's codepage. This means that it is impossible to open paths containing characters from other languages or other unicode characters. 

Please either rework the API's to use window's native UTF16 wchar_t paths and their associated functions when compiling for windows, or require that all paths be UTF8 and on windows internally translate UTF8 to UTF16 and use the wfopen functions when opening files. Translating UTF8 to UTF16 in C can be done by importing the C++ `MultiByteToWideChar` function as done by stb_image (see: [https://github.com/nothings/stb/blob/ae721c50eaf761660b4f90cc590453cdb0c2acd0/stb_image.h#L1325C49-L1325C68](https://github.com/nothings/stb/blob/ae721c50eaf761660b4f90cc590453cdb0c2acd0/stb_image.h#L1325C49-L1325C68))

**Comment by HappySeaFox** [comment]
Could you please attach a sample image with a non-ascii file name and a sample project reproducing the issue? I remember similar issues in the past, I just remember it was possible to workaround them. It would be great to have a sample minimal project and a sample image file.

**Comment by HappySeaFox** [comment]
If you build SAIL manually, you can try the git branch from the linked pull request.
