### ISSUE TITLE
Creating blank image for manipulation

### ISSUE THREAD

**Issue by Paril** [HappySeaFox/sail#211]
The one big thing I'm noticing is missing is that I can't create a SAIL-backed image for manipulation purposes; I can load an image from disk, create a new image with null pixels of WxH of a format, or create an image holding a shallow pointer to an existing block of memory, but I can't create an image and ask SAIL to allocate the required space for me to then work with (a hypothetical `sail::image(width, height, format)`). Currently my only option is to allocate the required space ahead of time, allocate a SAIL image pointing to it, perform operation(s) and then do a deep copy to a new `sail::image` so that it now owns the memory.

The justification for this is mainly to not need to lug around two different pointers, & that nearly every image library has the option to do  this sort of thing (think procedurally generated images or custom conversion routines that aren't currently supported by SAIL, like converting grayscale to a specified indexed palette or something).

**Comment by HappySeaFox** [comment]
Please try 30bf775

**Comment by Paril** [comment]
Thanks, I will check them out ASAP. A secondary question since I need to try a specific revision instead of just using vcpkg: what am I missing to get static linking working? I can get shared libs working no problem, but when trying with static, it seems to not be compiling in the created .c file from sail-codecs (`unresolved external symbol __imp_sail_enabled_codecs`, etc).

My setup is as follows:
```
set(SAIL_BUILD_APPS NO)
set(SAIL_BUILD_EXAMPLES NO)
set(BUILD_TESTING NO)
set(BUILD_SHARED_LIBS NO)
#SET(SAIL_COMBINE_CODECS YES)
SET(SAIL_ONLY_CODECS jpeg png pcx tga wal xbm)
add_subdirectory(thirdparty/sail)

target_link_libraries(qmdlr PRIVATE sail sail-c++ sail-codecs)
target_compile_definitions(qmdlr PRIVATE SAIL_STATIC)
```

If I swap SHARED_LIBS to yes (+ use combine codecs) and remove SAIL_STATIC it does work though, so at least I can test that way for now, but ideally I'd like to statically embed everything.

**Comment by HappySeaFox** [comment]
You can still use vcpkg, just update `REF` and `SHA512`  in `ports/sail/portfile.cmake` in your local vcpkg copy like that:

```
    REF master
    SHA512 4d6a6e61305c89aee94bd278f3c2f4e539c01802563e03d81ea25c0c03cfcab081866b0901b8462bda5800b1742ed70d592d7f84939dec2c04f3ff40c8fea352
```

>My setup is as follows:

With static libs, SAIL creates an extra library `sail-codecs-archive`. Try to link against it along with other sail libs. Be prepared to face linking errors against libjpeg and similar libraries. I'd recommend to use vcpkg.
