### ISSUE TITLE
Created an AUR package, is this workaround needed?

### ISSUE THREAD

**Issue by simoneee9** [HappySeaFox/sail#213]
Hi, I wanted to create a package for this library and submit it to the Arch User Repository. I created a PKGBUILD file, which is currently working correctly, but i had to do a little workaround at the end.

The problem is that once the library is built and installed, the path for the headers is wrong. All the headers are placed in `/usr/include/sail/sail-*` instead of `/usr/include/sail-*` - there is an extra `sail/` directory in the path.

I feel like this is not the expected behaviour, because when i try to use SAIL in my C++ code, i have to include everything like this

```cpp
#include <sail/sail-c++/image.h>
#include <sail/sail-common/common.h>
```

Clangd interprets this path as correct but it also makes compilation fail, because although the included headers are found, those headers are including more headers, but this time without the `sail/` prefix, and that causes it to fail (because the files cannot be found). I have tried to remove the prefix in these include statements, but that caused the compilation to fail even earlier.

I managed to solve the problem in the `package()` phase by simply getting rid of the extra `sail/` directory:

```sh
mv  $pkgdir/usr/include/sail" "$pkgdir/usr/include/sail-tmp"
mv "$pkgdir/usr/include/sail-tmp/"** "$pkgdir/usr/include/"
rm -r "$pkgdir/usr/include/sail-tmp"
``` 

But this feels kinda hacky... am I doing something wrong during the build?

Here is the full PKGBUILD
```sh
# Maintainer: Šimon Hacaj <hacajsimon@gmail.com>
pkgname="sail-img"
pkgver=0.9.5
pkgrel=1
pkgdesc="The missing small and fast image decoding library for humans (not for machines)"
arch=(x86_64)
url="https://github.com/HappySeaFox/sail"
license=('MIT')
depends=(
  'jasper' 'libwebp' 'giflib' 'libjpeg-turbo' 'libavif'
  'libjxl' 'libpng' 'libtiff' 'gcc-libs' 'glibc'
)
makedepends=('git' 'cmake')
provides=("libsail" "libsail-common" "libsail-c++" "libsail-manip")
source=(
  ${pkgname}-${pkgver}.tar.gz::https://github.com/HappySeaFox/sail/archive/refs/tags/v${pkgver}.tar.gz
)
sha256sums=('28c601c0399be1940710afc150b5836f8b3f5f6a35b98d7ac1467e62bc568e20')

prepare() {
  cd "${srcdir}/sail-${pkgver}"
  mkdir ./build -p
}

build() {
  cd "${srcdir}/sail-${pkgver}/build"
  cmake -DSAIL_BUILD_APPS=OFF -DSAIL_BUILD_EXAMPLES=OFF \
    -DCMAKE_INSTALL_PREFIX=/usr ..
  make
}

package() {
  cd "${srcdir}/sail-${pkgver}/build"
  make DESTDIR="$pkgdir/" install

  mv "$pkgdir/usr/include/sail" "$pkgdir/usr/include/sail-tmp"
  mv "$pkgdir/usr/include/sail-tmp/"** "$pkgdir/usr/include/"
  rm -r "$pkgdir/usr/include/sail-tmp"

  install -D -m644 ../LICENSE.txt "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
}
```

**Comment by HappySeaFox** [comment]
Hi! Thanks for the package!

The paths are correct. The user is supposed to use CMake and find_package which imports correct include paths. Alternatively, if the user doesn't want to use CMake, he or she needs to add /user/include/sail to the directory search path (-I). This way the use can include <sail/sail-c++.h>

**Comment by simoneee9** [comment]
alright, that makes sense. I will get rid of the workaround, thank you!
