### ISSUE TITLE
Including SAIL as a Subproject Requires Workaround in CMake for Setting Options

### ISSUE THREAD

**Issue by bedwardly-down** [HappySeaFox/sail#215]
Hey there.

I'm learning how to build my own engine tech and wanted to include your library in my build pipeline. Took a bit to figure out how to pass options down through an external CMakeLists.txt file. By default, they are ignored otherwise.

Platform: Fedora Linux 40 64-bit

Here's how I had to get the options I wanted to set working:

```
set(
  SAIL_INSTALL_PDB 
  OFF
  CACHE INTERNAL
  ""
)

set(
  SAIL_BUILD_APPS 
  OFF
  CACHE INTERNAL
  ""
)

set(
  SAIL_BUILD_EXAMPLES 
  OFF
  CACHE INTERNAL
  ""
)

set(
  SAIL_ONLY_CODECS 
  "tga"
  CACHE INTERNAL
  ""
)

set(
  BUILD_SHARED_LIBS 
  OFF
  CACHE INTERNAL
  ""
)

set(
  BUILD_TESTING 
  OFF
  CACHE INTERNAL
  ""
)

add_subdirectory(sail)
```

Not sure if this is something that needs to be tweaked in the configuration files but posting this here for anyone that needs it since it hasn't been posted previously. Can't wait to use Sail!!!

### How to Reproduce
1. Add Sail as a submodule for another git repository under a subdirectory (such as `vendor or thirdparty`
2. Set any variables in a CMakeLists.txt file that is one level above where sail is (but not necessarily top level)
3. Run cmake in top level directory
4. See that the option is ignored.

Any more information needed, feel free to ask. :)

-Brad

**Comment by HappySeaFox** [comment]
Hi! What's your CMake version? This looks very similar to https://cmake.org/cmake/help/latest/policy/CMP0077.html#policy:CMP0077 So in CMake 3.13+ setting normal SAIL_ variables in the top CMakeLists.txt should work as expected and the SAIL CMake configuration should honor them. In CMake 3.12 one should set cache variables in the top CMakeLists.txt.

**Comment by bedwardly-down** [comment]
I'm on version 3.28.2 . It works if I do it top level but I was looking to separate modules and whatnot. Setting CMP0077 to NEW only disabled the warning. Setting it at the top level for me could possibly pollute the other modules but adding as CACHE INTERNAL solved it for me.

Thanks for replying. :D

**Comment by HappySeaFox** [comment]
Please also note that some variables like SAIL_ONLY_CODECS are cache by default. This is done intentionally to document them for cmake-gui, as non-cache variables don't support documentation strings. This is why one needs to use set(... CACHE...) in the top CMakeLists.txt.
