### ISSUE TITLE
vcpkg include directories incorrect

### ISSUE THREAD

**Issue by shiiion** [HappySeaFox/sail#75]
It seems that when installing using vcpkg, the headers expect that the include root is in the `sail` directory, but vcpkg places the includes under `sail`. To include something in your own project, you need
```
#include <sail/sail-c++/sail-c++.h>
```
but the sail headers includes other sail headers as

```
#include <sail-c++/...>
```
Am I missing something here? Was this project updated since it was set up for vcpkg that caused this?

**Comment by HappySeaFox** [comment]
Hi! Do you use CMake? With CMake, you get correct include paths. Sample project:

**CMakeLists.txt**
```
cmake_minimum_required(VERSION 3.10)

project(SAIL VERSION 1.0.0
             DESCRIPTION "sail-probe"
             LANGUAGES C CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

add_executable(sail-probe sail-probe.cpp)

find_package(SailC++ REQUIRED)
target_link_libraries(sail-probe SAIL::sail-c++)
```

**sail-probe.cpp**
```
#include <sail-c++/sail-c++.h>

int main(int argc, char *argv[]) {

    sail::image_reader reader;
    sail::image image;

    SAIL_TRY(reader.probe(argv[1], &image));

    return 0;
}
```

**Compilation**
```
mkdir build
cd build
cmake -A x64 -DCMAKE_TOOLCHAIN_FILE=D:\projects\git.vcpkg.sail\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build . --config Release
```

**Running**
```
>Release\sail-probe.exe "D:/images/png/xin-gray-1bit.png"
SAIL: [D] [io_file.c:177] Opening file 'D:/images/png/xin-gray-1bit.png' in 'rb' mode
SAIL: [D] [context_private.c:696] Allocated a new thread-local context 00000000004FFF40
SAIL: [I] [context_private.c:655] Version 0.9.0
SAIL: [D] [context_private.c:54] Add 'D:\projects\sail-test\build\Release' to the DLL search paths
SAIL: [D] [context_private.c:181] SAIL_MY_CODECS_PATH environment variable is not set. Not loading codecs from it
SAIL: [D] [context_private.c:364] Enumerated codecs:
SAIL: [D] [context_private.c:369] 1. BMP [Bitmap Picture] 1.1.2
SAIL: [D] [context_private.c:369] 2. GIF [Graphics Interchange Format] 1.3.1
SAIL: [D] [context_private.c:369] 3. JPEG [Joint Photographic Experts Group] 1.3.4.1
SAIL: [D] [context_private.c:369] 4. PNG [Portable Network Graphics] 1.1.3
SAIL: [D] [context_private.c:369] 5. TIFF [Tagged Image File Format] 1.0.1
SAIL: [D] [context_private.c:677] Initialized in 27 ms.
SAIL: [D] [codec_info.c:115] Read magic number: '89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52'
SAIL: [D] [codec_info.c:126] Found codec info: 'PNG'
SAIL: [D] [helpers.c:330] PNG: Found ICC profile 'Dot Gain 20%' 912 bytes long
SAIL: [D] [palette-c++.cpp:129] NULL pointer has been passed to sail::palette(). The object is untouched
```

**Comment by HappySeaFox** [comment]
Please re-open in case of any issues.

**Comment by AlexMollard** [comment]
I am still having this issue and am trying not to use CMake, has this been fixed for Visual Studio 2022?
```
1>C:\vcpkg\installed\x64-windows-static\include\sail\sail\sail_junior.h(33,14): fatal  error C1083: Cannot open include file: 'sail-common/error.h': No such file or directory
```
It is the same wether I use x86, x64 or x64-static.

**Comment by HappySeaFox** [comment]
@AlexMollard  Do you use the MSVS vcpkg integration?

**Comment by AlexMollard** [comment]
Yeah, I am currently using a few other libraries without issue.

**Comment by AlexMollard** [comment]
Tried your suggestion but still am having trouble, All files are being linked now but can't seem to figure out why `SailPixelFormat` is unknown.
```
> In file included from C:\vcpkg\installed\x64-windows\include\sail/sail-c++/image-c++.h:38:
> C:\vcpkg\installed\x64-windows\include\sail/sail-c++/palette-c++.h(65,13): error : unknown type name 'SailPixelFormat'
```

**Comment by HappySeaFox** [comment]
Oh, I see. I didn't notice this error before as I use universal sail headers. I think you can try the following potential fixes:

1. Use universal includes: `#include <sail-c++/sail-c++.h>`. They already include `sail-common/common.h` with the necessary definition
2. Or, include `sail-common/common.h` before including any sail cpp headers.

**Comment by HappySeaFox** [comment]
There may be more errors like take. I've just pushed several fixes.

Until the fixes reach vcpkg, **using universal includes is recommended**.

**Comment by HappySeaFox** [comment]
SAIL-RC2 with the missing includes fix has been merged into vcpkg. Please update the local copy of vcpkg and install rc2. Adding VcpkgInstalledDir/include/sail to the project include path is still required if you don't use cmake.
