### ISSUE TITLE
image_reader-c++.h missing in the latest vcpkg version?

### ISSUE THREAD

**Issue by jsobiers** [HappySeaFox/sail#93]
After pulling the latest version of vcpkg (commit: 2f573976e68cc1ededbfa811adb4475dea321872) and getting the latest version of SAIL (0.9.0-pre14), the image_reader-c++.h is missing in the include directory.
Is it intentional?

**Comment by HappySeaFox** [comment]
Hi, @jsobiers ! image_reader has been renamed to image_input in the latest version. Sorry for inconvenience! SAIL API abd ABI is still not freezed. You can expect api and abi change before the final release of 0.9.0.

**Comment by jsobiers** [comment]
Thanks for quick reply, works like a charm.
